config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "details", to: 'home#details'
  resources :rooms do
    resources :reports, only: [:index, :new, :create, :destroy]
  end
  resources :subjects, only: [:index, :new, :create, :destroy] do
    resources :memos do
      collection do
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
    member do
      get 'library'
    end
  end
  resources :chats, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  resources :articles do
    member do
      post 'edit_confirm'
      post 'edit_back'
    end
    collection do
      post 'confirm'
      post 'back'
      get 'search'
      get 'tagsearch'
    end
    resource :likes, only: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :study_genre
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations
  has_many :users, through: :likes
  has_many :likes
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :study_genre_id
  end
  with_options presence: true do
    validates :summary
    validates :detail
  end

  def self.search(search, study_genre, tag)
    if tag.present?
      Tag.find(tag).articles
    elsif search != '' && study_genre != '1'
      Article.where('summary LIKE(?)',
                    "%#{search}%").or(Article.where('detail LIKE(?)',
                                                    "%#{search}%")).where(study_genre_id: study_genre)
    elsif search != '' && study_genre == '1'
      Article.where('summary LIKE(?)',
                    "%#{search}%").or(Article.where('detail LIKE(?)',
                                                    "%#{search}%"))
    elsif search == '' && study_genre != '1'
      Article.where(study_genre_id: study_genre)
    else
      Article.all
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_article, only: [:show, :edit]
  def index
    @articles = Article.all.order(created_at: 'DESC')
  end

  def new
    @article = ArticlesTag.new
  end

  def back
    @article = ArticlesTag.new(article_params)
    render :new
  end

  def confirm
    @article = ArticlesTag.new(article_params)
    render :new if @article.invalid?
  end

  def create
    @article = ArticlesTag.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def show
  end

  def edit
    redirect_to root_path unless user_signed_in? && @article.user == current_user
    @tag = @article.tags.pluck(:tag_name).join(',')
    @form = ArticlesTag.new(summary: @article.summary, detail: @article.detail, study_genre_id: @article.study_genre_id,
                            tag_name: @tag)
  end

  def edit_back
    @form = ArticlesTag.new(update_params)
    render :edit
  end

  def edit_confirm
    @form = ArticlesTag.new(update_params)
    render :edit if @form.invalid?
  end

  def update
    @form = ArticlesTag.new(update_params)
    @form.update
    redirect_to articles_path
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

  def search
    @articles = Article.search(params[:keyword], params[:study_genre_id], params[:tag_id]).order(created_at: 'DESC')
  end

  def tagsearch
    return nil if params[:keyword] == ''

    tag = Tag.where(['tag_name LIKE ?', "%#{params[:keyword]}%"])
    render json: { keyword: tag }
  end

  private

  def article_params
    params.require(:articles_tag).permit(:study_genre_id, :summary, :detail, :tag_name).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:articles_tag).permit(:study_genre_id, :summary, :detail, :tag_name).merge(user_id: current_user.id,
                                                                                              article_id: params[:id])
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/confirm.html.erb
<%= render "shared/article_header"%>

<div class="article-show-wrapper">
  <div class="article-wrapper-body">
    <h1 class="confirm-title">記事本文の確認</h1>
    <div class="article-main">
      <%= sanitize markdown(@article.detail), tags: %w(h1 h2 h3 h4 h5 strong em a p ul li code pre a), attributes: %w(href) %>
    </div>
    <div class="confirm-btns">
      <%= form_with model: @article, method: :post, url: articles_path, class:"confirm-btn", local: true do |f| %>
        <%= f.hidden_field :summary %>
        <%= f.hidden_field :study_genre_id %>
        <%= f.hidden_field :tag_name %>
        <%= f.hidden_field :detail %>
        <%= f.submit '送信する', class: 'confirm-create' %>
      <% end %>

      <%= form_with model: @article, method: :post, url: back_articles_path, class:"confirm-btn", local: true do |f| %>
        <%= f.hidden_field :summary %>
        <%= f.hidden_field :study_genre_id %>
        <%= f.hidden_field :tag_name %>
        <%= f.hidden_field :detail %>
        <%= f.submit '入力画面に戻る', class: 'confirm-back' %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/articles/edit.html.erb
<%= render "shared/article_header"%>

<div class="article-new-form">
  <%= form_with model: @form, url: edit_confirm_article_path, method: :post, class: 'registration-main', local: true do |f| %>
  <div class="form-wrap">
    <div class='form-header'>
      <h1 class='form-header-text'>
        記事の編集
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :summary, '記事タイトル', class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :summary, placeholder: '最大40文字まで', class:"input-default", maxlength: "40" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :study_genre_id, "ジャンル", class: "form-text"%>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"input-default"}) %>
    </div>
    <div class="form-group-wide">
      <div class="form-text-wrap">
        <%= f.label :tag_name, "タグ", class: "form-text" %>
      </div>
      <%= f.text_field :tag_name, class:"input-default" %>
    </div>
    <div class="form-group-wide">
      <div class="form-text-wrap">
        <%= f.label :detail, '本文', class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <div class="article-detail">
        <%= f.text_area :detail, placeholder: '本文を記入してください。マークダウン記法が可能です。', class: "input-article-detail" %>
      </div>
    </div>
    <div class="register-btn">
      <%= f.submit "記事更新", class: 'register-link' %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/articles/edit_confirm.html.erb
<%= render "shared/article_header"%>

<div class="article-show-wrapper">
  <div class="article-wrapper-body">
    <h1 class="confirm-title">記事本文の確認</h1>
    <div class="article-main">
      <%= sanitize markdown(@form.detail), tags: %w(h1 h2 h3 h4 h5 strong em a p ul li code pre a), attributes: %w(href) %>
    </div>
    <div class="confirm-btns">
      <%= form_with model: @form, method: :patch, url: article_path, class:"confirm-btn", local: true do |f| %>
        <%= f.hidden_field :summary %>
        <%= f.hidden_field :study_genre_id %>
        <%= f.hidden_field :tag_name %>
        <%= f.hidden_field :detail %>
        <%= f.submit '送信する', class: 'confirm-create' %>
      <% end %>

      <%= form_with model: @form, method: :post, url: edit_back_article_path, class:"confirm-btn", local: true do |f| %>
        <%= f.hidden_field :summary %>
        <%= f.hidden_field :study_genre_id %>
        <%= f.hidden_field :tag_name %>
        <%= f.hidden_field :detail %>
        <%= f.submit '入力画面に戻る', class: 'confirm-back' %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/articles/index.html.erb
<%= javascript_pack_tag "search.js" %>
<% if user_signed_in? %>
  <%= render "shared/article_header" %>
<% else %>
  <%= render "shared/logout_article_header" %>
<% end %>
<div class="article-wrapper">
  <div class="article-search-bar">
    <div class="article-search-body">
      <h4 class="article-search-title">ジャンル/フリーワード検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-box">
          <div class="article-search-field">
            <%= f.label :study_genre_id, "ジャンル", class:"search-article" %>
            <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"article-search-input"}) %>
          </div>
          <div class="article-search-field">
            <%= f.label :keyword, "フリーワード検索", class:"search-article" %>
            <%= f.text_field :keyword, placeholder: "記事を検索する", class: "article-search-input" %>
          </div>
          <div class="article-search-btn-field">
            <%= f.submit "検索", class: "search-btn" %>
          </div>
        </div>
      <% end %>
      <h4 class="article-search-title">タグで検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-field">
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み',
              class: 'article-search-input',
              onchange: 'submit(this.form)'
            }%>
        </div>
      <% end %>
    </div>
  </div>
  <div id="search-box">
    <i class="fas fa-search"></i>
  </div>
  
  <div id="hidden">
    <div class="article-search-body">
      <h4 class="article-search-title">ジャンル/フリーワード検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-box">
          <div class="article-search-field">
            <%= f.label :study_genre_id, "ジャンル", class:"search-article" %>
            <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"article-search-input"}) %>
          </div>
          <div class="article-search-field">
            <%= f.label :keyword, "フリーワード検索", class:"search-article" %>
            <%= f.text_field :keyword, placeholder: "記事を検索する", class: "article-search-input" %>
          </div>
          <div class="article-search-btn-field">
            <%= f.submit "検索", class: "search-btn" %>
          </div>
        </div>
      <% end %>
      <h4 class="article-search-title">タグで検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-field">
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み',
              class: 'article-search-input',
              onchange: 'submit(this.form)'
            }%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="article-body">
    <div class="article-header">
      <h3 class="article-title">記事一覧</h3>
      <div class="article-header-right">
        <%= link_to '記事作成', new_article_path, class: 'article-new' %>
      </div>
    </div>
    
    
    <div class="article-lists">
      <% @articles.each do |article| %>
        <%= link_to article_path(article) do %>
          <div class="article-list">
            <div class="list-upper">
              <h3 class="article-summary"><%= article.summary %></h3>
            </div>
            <p class="article-genre"><%= article.study_genre.name %></p>
            <div class="list-bottom">
                
                <div class="bottom-left-bottom">
                  <div class="list-like">
                    <p><%= "お気に入り:#{article.likes.count}" %></p>
                  </div>
                  <div class="list-tag">
                    <% if article.tags.present? %>
                      <% article.tags.each do |tag| %>
                        <p class="list-tag-name">#<%= tag.tag_name %></p>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <div class="bottom-right">
                <div class="list-user">
                  <p class="list-user-nickname">投稿者:<%= article.user.nickname %></p>
                  <p class="list-article-date">最終更新日時: <%= l article.updated_at, format: :long %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/articles/new.html.erb
<%= render "shared/article_header"%>

<div class="article-new-form">
  <%= form_with model: @article, url: confirm_articles_path, class: 'registration-main', local: true do |f| %>
  <div class="form-wrap">
    <div class='form-header'>
      <h1 class='form-header-text'>
        記事の作成
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :summary, '記事タイトル', class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :summary, placeholder: '最大40文字まで', class:"input-default", maxlength: "40" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :study_genre_id, "ジャンル", class: "form-text"%>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"input-default"}) %>
    </div>
    <div class="form-group-wide">
      <div class="form-text-wrap">
        <%= f.label :tag_name, "タグ", class: "form-text" %>
      </div>
      <%= f.text_field :tag_name, class:"input-default" %>
      <div class="search-result-list">
        <p>候補</p>
        <div id="search-result">
        </div>
      </div>
    </div>
    <div class="form-group-wide">
      <div class="form-text-wrap">
        <%= f.label :detail, '本文', class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <div class="article-detail">
        <%= f.text_area :detail, placeholder: '本文を記入してください。マークダウン記法が可能です。', class: "input-article-detail" %>
      </div>
    </div>
    <div class="register-btn">
      <%= f.submit "記事投稿", class: 'register-link' %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer"%>

app/views/articles/search.html.erb
<%= javascript_pack_tag "search.js" %>
<% if user_signed_in? %>
  <%= render "shared/article_header" %>
<% else %>
  <%= render "shared/logout_article_header" %>
<% end %>
<div class="article-wrapper">
  <div class="article-search-bar">
    <div class="article-search-body">
      <h4 class="article-search-title">ジャンル/フリーワード検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-box">
          <div class="article-search-field">
            <%= f.label :study_genre_id, "ジャンル", class:"search-article" %>
            <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"article-search-input"}) %>
          </div>
          <div class="article-search-field">
            <%= f.label :keyword, "フリーワード検索", class:"search-article" %>
            <%= f.text_field :keyword, placeholder: "記事を検索する", class: "article-search-input" %>
          </div>
          <div class="article-search-btn-field">
            <%= f.submit "検索", class: "search-btn" %>
          </div>
        </div>
      <% end %>
      <h4 class="article-search-title">タグで検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-field">
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み',
              class: 'article-search-input',
              onchange: 'submit(this.form)'
            }%>
        </div>
      <% end %>
    </div>
  </div>
  <div id="search-box">
    <i class="fas fa-search"></i>
  </div>
  
  <div id="hidden">
    <div class="article-search-body">
      <h4 class="article-search-title">ジャンル/フリーワード検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-box">
          <div class="article-search-field">
            <%= f.label :study_genre_id, "ジャンル", class:"search-article" %>
            <%= f.collection_select(:study_genre_id, StudyGenre.all, :id, :name, {}, {class:"article-search-input"}) %>
          </div>
          <div class="article-search-field">
            <%= f.label :keyword, "フリーワード検索", class:"search-article" %>
            <%= f.text_field :keyword, placeholder: "記事を検索する", class: "article-search-input" %>
          </div>
          <div class="article-search-btn-field">
            <%= f.submit "検索", class: "search-btn" %>
          </div>
        </div>
      <% end %>
      <h4 class="article-search-title">タグで検索</h4>
      <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
        <div class="article-search-field">
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み',
              class: 'article-search-input',
              onchange: 'submit(this.form)'
            }%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="article-body">
    <div class="article-header">
      <h3 class="article-title">記事一覧</h3>
      <div class="article-header-right">
        <%= link_to '記事作成', new_article_path, class: 'article-new' %>
      </div>
    </div>
    
    
    <div class="article-lists">
      <% @articles.each do |article| %>
        <%= link_to article_path(article) do %>
          <div class="article-list">
            <div class="list-upper">
              <h3 class="article-summary"><%= article.summary %></h3>
            </div>
            <p class="article-genre"><%= article.study_genre.name %></p>
            <div class="list-bottom">
                
                <div class="bottom-left-bottom">
                  <div class="list-like">
                    <p><%= "お気に入り:#{article.likes.count}" %></p>
                  </div>
                  <div class="list-tag">
                    <% article.tags.each do |tag| %>
                      <p class="list-tag-name">#<%= tag.tag_name %></p>
                    <% end %>
                  </div>
                </div>
              <div class="bottom-right">
                <div class="list-user">
                  <p class="list-user-nickname">投稿者:<%= article.user.nickname %></p>
                  <p class="list-article-date">最終更新日時: <%= l article.updated_at, format: :long %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/articles/show.html.erb
<% if user_signed_in? %>
  <%= render "shared/article_header" %>
<% else %>
  <%= render "shared/logout_article_header" %>
<% end %>


<div class="article-show-wrapper">
  <div class="article-wrapper-body">
    <div class="article-show-header">
      <div class="article-header-upper">
        <div class="article-upper-upper">
          <div class="article-title">
            <h3 class="article-title-summary"><%= @article.summary %></h3>
          </div>
          <div class="article-genre-show">
            <p>ジャンル:<%= @article.study_genre.name %></p>
          </div>
        
        </div>
        <div class="article-upper-bottom">
          <div class="article-date-show">
            <p>最終更新日時: <%= l @article.updated_at, format: :long %></p>
          </div>
          <div class="article-user-show">
            <p>投稿者: </p><%= link_to @article.user.nickname, user_path(@article.user) %>
          </div>
        </div>
      </div>
      <div class="article-header-bottom">
        <div class="article-tags">
          <% @article.tags.each do |tag| %>
            <div class="article-tag">
              <p>#<%= tag.tag_name %></p>
            </div>
          <% end %>
        </div>
      </div>
      <div class="like-btn">
        <% if user_signed_in? %>
          <% if @article.liked_by?(current_user) %>
            <p><%= link_to "お気に入り解除: #{@article.likes.count}", article_likes_path(@article.id), class:'like-btn-blue', method: :delete %></p>
          <% else %>
            <p><%= link_to "お気に入り登録: #{@article.likes.count}", article_likes_path(@article.id), class:'like-btn-white', method: :post %></p>
          <% end %>
        <% else %>
          <p class="like-btn-grey"><span>お気に入り数: </span><%= @article.likes.count %></p>
        <% end %>
        <% if user_signed_in? && @article.user.id == current_user.id %>
          <div class="links-edit-destroy">
            <p><%= link_to "編集", edit_article_path(@article), class:'edit-link' %></p>
            <p><%= link_to "削除", article_path(@article), method: :delete, class:'edit-link', data: { confirm: "本当に削除しますか？" } %>
          </div>
        <% end %>
      </div>
  
      <div class="article-main" id="article-main">
        <%= sanitize markdown(@article.detail), tags: %w(h1 h2 h3 h4 h5 strong em a p ul li code pre a), attributes: %w(href) %>
      </div>
    </div>
    

  </div>
</div>

<%= render "shared/footer"%>