config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "details", to: 'home#details'
  resources :rooms do
    resources :reports, only: [:index, :new, :create, :destroy]
  end
  resources :subjects, only: [:index, :new, :create, :destroy] do
    resources :memos do
      collection do
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
    member do
      get 'library'
    end
  end
  resources :chats, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  resources :articles do
    member do
      post 'edit_confirm'
      post 'edit_back'
    end
    collection do
      post 'confirm'
      post 'back'
      get 'search'
      get 'tagsearch'
    end
    resource :likes, only: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :study_genre
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations
  has_many :users, through: :likes
  has_many :likes
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :study_genre_id
  end
  with_options presence: true do
    validates :summary
    validates :detail
  end

  def self.search(search, study_genre, tag)
    if tag.present?
      Tag.find(tag).articles
    elsif search != '' && study_genre != '1'
      Article.where('summary LIKE(?)',
                    "%#{search}%").or(Article.where('detail LIKE(?)',
                                                    "%#{search}%")).where(study_genre_id: study_genre)
    elsif search != '' && study_genre == '1'
      Article.where('summary LIKE(?)',
                    "%#{search}%").or(Article.where('detail LIKE(?)',
                                                    "%#{search}%"))
    elsif search == '' && study_genre != '1'
      Article.where(study_genre_id: study_genre)
    else
      Article.all
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/articles_tag.rb
class ArticlesTag
  include ActiveModel::Model
  attr_accessor :user_id, :article_id, :summary, :study_genre_id, :detail, :tag_name

  with_options presence: true do
    validates :summary
    validates :detail
  end
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :study_genre_id
  end

  def save
    article = Article.create(user_id: user_id, summary: summary, study_genre_id: study_genre_id, detail: detail)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save

    ArticleTagRelation.create(article_id: article.id, tag_id: tag.id)
  end

  def update
    @article = Article.where(id: article_id)
    article = @article.update(user_id: user_id, summary: summary, study_genre_id: study_genre_id, detail: detail)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save

    map = ArticleTagRelation.where(article_id: article_id)
    map.update(article_id: article_id, tag_id: tag.id)
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :chat_users, dependent: :destroy
  has_many :users, through: :chat_users
  has_many :messages, dependent: :destroy
end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_one_attached :image
  validates :topic, presence: true

  def self.search(search)
    if search != ''
      Memo.where('topic LIKE(?)',
                 "%#{search}%").or(Memo.where('point LIKE(?)',
                                              "%#{search}%")).or(Memo.where('explanation LIKE(?)', "%#{search}%"))
    else
      Memo.all
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
  validates :content, presence: true
  def template
    ApplicationController.renderer.render partial: 'messages/message', locals: { message: self }
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :room
  with_options presence: true do
    validates :study_time
    validates :concentrated_time
    validates :good_way
    validates :tomorrow_plan
    validates :study_content
    validates :advice
  end
  validates :achieved, inclusion: { in: [true, false] }
  validates :go_wrong, presence: true, unless: :achieved
  validate :concentrated_check

  def concentrated_check
    if study_time.present? && concentrated_time.present? && concentrated_time > study_time
      errors.add(:concentrated_time,
                 'が本日の学習時間を超えないようにしてください')
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users, validate: false
  has_many :reports, dependent: :destroy
  has_one_attached :image
  with_options presence: true do
    validates :title
    validates :purpose_room
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :user, optional: true
end

app/models/study_genre.rb
class StudyGenre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'プログラミング' },
    { id: 3, name: '資格系(FP/宅建/簿記等)' },
    { id: 4, name: '英語系(TOEIC/英検等)' },
    { id: 5, name: 'デザイン/動画制作' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :articles
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :memos, dependent: :destroy
  validates :name, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tag_relations
  has_many :articles, through: :article_tag_relations

  validates :tag_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には半角英字と半角数字を両方含めてください'
  with_options presence: true do
    validates :nickname
    validates :birthday
  end
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :study_genre_id
  end
  validates :email, uniqueness: { case_sensitive: false }
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :reports
  has_many :subjects
  has_many :memos
  has_many :chat_users
  has_many :chats, through: :chat_users
  has_many :messages
  has_many :articles
  has_many :likes, dependent: :destroy
  has_many :like_articles, through: :likes, source: :article
  belongs_to_active_hash :study_genre

  def self.search(search, study_genre)
    if search != '' && study_genre != '1'
      User.where('nickname LIKE(?)',
                 "%#{search}%").or(User.where('self_introduction LIKE(?)',
                                              "%#{search}%")).where(study_genre_id: study_genre)
    elsif search != '' && study_genre == '1'
      User.where('nickname LIKE(?)',
                 "%#{search}%").or(User.where('self_introduction LIKE(?)',
                                              "%#{search}%"))
    elsif search == '' && study_genre != '1'
      User.where(study_genre_id: study_genre)
    else
      User.all
    end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_article_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "current-nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "current-nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <% if user_signed_in? %>
    <div class="header-right">
      <ul class='right-lists'>
        <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
        <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
        <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
        <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
        <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
        <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
      </ul>
      <div id="box">
        <span></span>
      </div>
    </div>

    <nav>
      <ul class='sp-right-lists'>
        <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
        <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
        <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
        <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
        <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
        <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
      </ul>
    </nav>
    
  <% else %>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Top', root_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
    </ul>
  </div>
  <% end %>
</header>

app/views/shared/_logout_user_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>
  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_logout_users_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>
  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_main_report.html.erb
<div class="main-main">
<!--collectionのあとの@messagesの数だけ部分テンプレート(_message.html.erb)が繰り返される-->
  <% @reports.each do |report| %>
    <% if report.user == current_user %>
      <div class="reports-mine">
        <%= render partial:'shared/report', locals: {report: report} %>
        <%= link_to '削除', "reports/#{report.id}", method: :delete, class:'report-destroy' %>
      </div>
    <% else %>
      <div class="reports-others">
        <%= render partial:'shared/report', locals: {report: report} %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_memo_main.html.erb
<div class="memo-main-wrapper">
  <div class="memo-main-header">
    <div class="memo-main-header-left">
      <h3 class="memo-main-header-title">メモ一覧</h3>
      <div class="memo-subject-name-wrapper">
        <h3 class="memo-subject-name"><%= @subject.name %></h3>
      </div>
    </div>
    <div class="memo-main-header-right">
      <%= link_to 'メモ新規作成', new_subject_memo_path(@subject), class: 'memo-new' %>
    </div>
  </div>
  <div class="memo-search">
    <%= form_with(url: search_subject_memos_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "メモを検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class="memo-contents">
    <ul class="memo-lists">
      <% @memos.each do |memo| %>
        <%= link_to subject_memo_path(@subject, memo) do %>
          <li class="memo-list">
            <div class="memo-topic">
              <%= memo.topic %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_mypage_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "current-nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "current-nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_registration_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "current-nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>
  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "current-nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_report_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_report_main.html.erb
<div class="main-main">
<!--collectionのあとの@messagesの数だけ部分テンプレート(_message.html.erb)が繰り返される-->
  <% @reports.each do |report| %>
    <% if report.user == current_user %>
      <div class="reports-mine">
        <%= render partial:'shared/report', locals: {report: report} %>
        <%= link_to '削除', "reports/#{report.id}", method: :delete, class:'report-destroy', data: { confirm: "本当に削除しますか？" } %>
      </div>
    <% else %>
      <div class="reports-others">
        <%= render partial:'shared/report', locals: {report: report} %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_room_header.html.erb
<%# <header class='report-header'>
  <div class='nav-report'>
    <ul class='lists-left'>
      <li><%= link_to @room.title, room_path(@room), class: "category-list" %></li>
    <%# </ul>
    <ul class='lists-right'>
      <li><%= link_to 'メモ', subjects_path, class: "subjects" %></li>
      <%# <li><%= link_to 'トップページ', root_path , class: "top-link" %></li>
      <%# <li><%= link_to '学習報告を行う', new_room_report_path(@room) , class: "new-report" %></li>
    <%# </ul>
  </div>
</header> %>
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_session_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "current-nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>
  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "nav-button" %></li>
      <li><%= link_to 'New Member', new_user_registration_path , class: "nav-button" %></li>
      <li><%= link_to 'Login', new_user_session_path , class: "current-nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_user_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>

app/views/shared/_users_header.html.erb
<%= javascript_pack_tag "menu.js" %>
<header class='home-header'>
  <ul class='header-left'>
    <li><%= link_to 'StudyReport', root_path, class: "header-logo" %></li>
  </ul>
  <div class="header-right">
    <ul class='right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
    <div id="box">
      <span></span>
    </div>
  </div>

  <nav>
    <ul class='sp-right-lists'>
      <li><%= link_to 'Report', rooms_path, class: "nav-button" %></li>
      <li><%= link_to 'Memo', subjects_path, class: "nav-button" %></li>
      <li><%= link_to 'Article', articles_path, class: "nav-button" %></li>
      <li><%= link_to 'MyPage', user_path(current_user), class: "nav-button" %></li>
      <li><%= link_to 'Users', users_path, class: "current-nav-button" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path , method: :delete, class: "nav-button" %></li>
    </ul>
  </nav>
</header>