config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "details", to: 'home#details'
  resources :rooms do
    resources :reports, only: [:index, :new, :create, :destroy]
  end
  resources :subjects, only: [:index, :new, :create, :destroy] do
    resources :memos do
      collection do
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
    member do
      get 'library'
    end
  end
  resources :chats, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  resources :articles do
    member do
      post 'edit_confirm'
      post 'edit_back'
    end
    collection do
      post 'confirm'
      post 'back'
      get 'search'
      get 'tagsearch'
    end
    resource :likes, only: [:create, :destroy]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users, validate: false
  has_many :reports, dependent: :destroy
  has_one_attached :image
  with_options presence: true do
    validates :title
    validates :purpose_room
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update]
  def index
    @rooms = Room.all.order(created_at: 'DESC')
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    render :new unless @room.save
  end

  def show
    redirect_to root_path unless user_signed_in? && @room.users.include?(current_user)
  end

  def edit
    redirect_to root_path unless user_signed_in? && @room.users.include?(current_user)
  end

  def update
    render :edit unless @room.update(room_params)
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
  end

  private

  def room_params
    params.require(:room).permit(:image, :title, :purpose_room, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/create.html.erb
<%= render "shared/report_header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">学習報告ルーム作成が完了しました!</h2>
    </div>
  </div>
  <div class='feature-lists'>
    <div class='list'>
      <%= link_to "学習報告ルームへ", room_reports_path(@room), class: 'link-room' %>
    </div>
    <div class='list'>
      <%= link_to "一覧に戻る", rooms_path, class: 'link-top' %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/destroy.html.erb
<%= render "shared/header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">学習報告ルームを削除しました</h2>
    </div>
  </div>
  <div class='feature-lists'>
    <div class='list'>
      <%= link_to "一覧に戻る", rooms_path, class:"link-top" %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/edit.html.erb
<%= render "shared/header"%>

<div class="registration-body">
  <%= form_with model: @room, url: room_path(@room), class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h2 class='form-header-text'>
        学習報告ルーム情報編集
      </h2>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ルーム画像</label>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, class:"room-image" %>
      </div>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <%= f.label :title, "ルーム名", class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"input-default", placeholder:"例) rails勉強会", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <%= f.label :purpose_room, "学習報告ルームの目的", class:"form-text" %>
        <span class="indispensable">※140字まで</span>
      </div>
      <%= f.text_area :purpose_room, class:"input-introduction", placeholder:"ルームの説明（学習テーマ、目的、学習目標等）例) Ruby on Railsの学習報告ルームです。webエンジニアを目指して学習を行っていきましょう。平日2時間、休日8時間学習しましょう", maxlength:"140" %>
    </div>
      <!-- これで現在ログインしているユーザーの情報も含められる -->
    <% @room.users.each do |user| %>
      <input name="room[user_ids][]" type="hidden" value=<%= user.id %>>
    <% end %>
    

    <div class="form-group">
      <h2 class='form-bottom-text'>
        「ルーム情報更新」ボタンを押すと、学習報告ルームの情報が更新されます。
      </h2>
      <div class='register-btn'>
        <%= f.submit "ルーム情報更新" ,class:"register-link" %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer"%>

app/views/rooms/index.html.erb
<%= render "shared/report_header" %>
<div class='room-wrapper'>
  <div class="room-body">
    <div class="room-header">
      <h3 class="room-title">あなたの学習報告ルーム</h3>
      <div class="room-header-right">
        <%= link_to "ルーム新規作成", new_room_path, class: 'room-new' %>
      </div>
    </div>
    <div class='room-lists'>
      <%# ユーザーの報告ルームが存在する場合表示 %>
        <%# ルーム毎に表示 %>
      <% @rooms.each do |room| %>
        <% if room.users.include?(current_user) %>
          <div class="got-list">
            <%= link_to room_path(room) do %>
              <div class='room-img-content'>
                <% if room.image.attached? %>
                  <%= image_tag room.image, class: "room-img" %>
                <% else %>
                  <%= image_tag 'report_human.jpg', class:"room-img" %>
                <% end %>
              </div>
              <div class='room-info'>
                <h3 class='room-name'>
                  <%= room.title %>
                </h3>
              </div>
            <% end %>
            <%= link_to '報告へ', room_reports_path(room), class: 'report-link' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class='new-message'>
      <div class='room-info'>
        <h3 class='room-message'>
          仲間と学習報告を行いましょう!
        </h3>
      </div>
    </div>
  </div>
</div>


<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/report_header"%>

<div class="registration-body">
  <%= form_with model: @room, url: rooms_path(@room), class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h2 class='form-header-text'>
        学習報告ルーム新規作成
      </h2>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ルーム画像</label>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, class:"room-image-upload" %>
      </div>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <%= f.label :title, "ルーム名", class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"input-default", placeholder:"例) rails勉強会", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <%= f.label :purpose_room, "学習報告ルームの目的", class:"form-text" %>
        <span class="indispensable">※140字まで</span>
      </div>
      <%= f.text_area :purpose_room, class:"input-introduction", placeholder:"ルームの説明（学習テーマ、目的、学習目標等）例) Ruby on Railsの学習報告ルームです。webエンジニアを目指して学習を行っていきましょう。平日2時間、休日8時間学習しましょう", maxlength:"140" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">メンバーを選択してください</label>
      </div>
      <select id="room_user" name="room[user_ids][]" >
        <option value="">ユーザーを選択してください</option>
        <% User.where.not(id: current_user.id).each do |user| %>
          <option value=<%= user.id %>><%= user.nickname %></option>
        <% end %>
      </select>
      <!-- これで現在ログインしているユーザーの情報も含められる -->
      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
    </div>
    

    <div class="form-group">
      <h2 class='form-bottom-text'>
        「ルーム作成」ボタンを押すと、学習報告ルームが生成されます。
      </h2>
      <div class='register-btn'>
        <%= f.submit "ルーム作成" ,class:"register-link" %>
      </div>
    </div>
    
  </div>
  <% end %>
</div>
<%= render "shared/footer"%>

app/views/rooms/show.html.erb
<%= render "shared/report_header" %>

<div class="room-show">
  <div class="room-box">
    <h2 class="name">
      <%= @room.title %>
    </h2>
    <div class='room-img-content'>
      <% if @room.image.attached? %>
        <%= image_tag @room.image, class: "room-box-img" %>
      <% else %>
        <%= image_tag 'report_human.jpg', class:"room-box-img" %>
      <% end %>
    </div>

    <% if user_signed_in? && @room.users.include?(current_user) %>
      <div class="to-report">
        <%= link_to "学習報告ルームへ", room_reports_path(@room), class:"room-link" %>
      </div>
    <% end %>

  
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-room">ルームの目的</th>
          <td class="detail-value"><%= @room.purpose_room %></td>
        </tr>
        <tr>
          <th class="detail-room">参加者</th>
          <td class="detail-value">
            <% @room.users.each do |user| %>
              <%= link_to user.nickname, user_path(user), class:"user-name" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="detail-room">最終投稿日時</th>
          <td class="detail-value">
            <% if @room.reports.present? %>
              <% @room.reports.last(1).each do |report| %>
                <%= l report.created_at, format: :short %>
              <% end %>
            <% else %>
              報告がありません
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? && @room.users.include?(current_user) %>
      <div class="room-edit-btn">
        <%= link_to 'ルーム情報の編集', edit_room_path(@room) , method: :get, class: "room-link-edit" %>
        <p class='or-text'>or</p>
        <%= link_to 'ルームの削除', room_path(@room), method: :delete, class:'room-link-des', data: { confirm: "本当に削除しますか？" } %>
      </div>
    <% end %>
    <div class="to-room-index">
      <%= link_to "一覧ページに戻る", rooms_path, class:"room-link" %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/update.html.erb
<%= render "shared/report_header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">学習報告ルーム編集が完了しました!</h2>
    </div>
  </div>
  <div class='feature-lists'>
    <div class='list'>
      <%= link_to "学習報告ルームへ", room_reports_path(@room), class: 'link-room' %>
    </div>
    <div class='list'>
      <%= link_to "一覧に戻る", rooms_path, class: 'link-top' %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>