config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "details", to: 'home#details'
  resources :rooms do
    resources :reports, only: [:index, :new, :create, :destroy]
  end
  resources :subjects, only: [:index, :new, :create, :destroy] do
    resources :memos do
      collection do
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
    member do
      get 'library'
    end
  end
  resources :chats, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  resources :articles do
    member do
      post 'edit_confirm'
      post 'edit_back'
    end
    collection do
      post 'confirm'
      post 'back'
      get 'search'
      get 'tagsearch'
    end
    resource :likes, only: [:create, :destroy]
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_one_attached :image
  validates :topic, presence: true

  def self.search(search)
    if search != ''
      Memo.where('topic LIKE(?)',
                 "%#{search}%").or(Memo.where('point LIKE(?)',
                                              "%#{search}%")).or(Memo.where('explanation LIKE(?)', "%#{search}%"))
    else
      Memo.all
    end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subject
  before_action :set_memo, only: [:show, :edit, :update]
  def index
    redirect_to root_path unless user_signed_in? && @subject.user_id == current_user.id
    @memos = @subject.memos.includes(:user).order(created_at: 'DESC')
    @subjects = Subject.where(user_id: current_user.id).where.not(id: params[:subject_id])
    # @subjects = Subject.where(user_id: current_user.id).where.not(params[:subject_id])
  end

  def new
    redirect_to root_path unless user_signed_in? && @subject.user == current_user
    @memo = Memo.new
  end

  def create
    @memo = @subject.memos.new(memo_params)
    render :new unless @memo.save
  end

  def show
    redirect_to root_path unless user_signed_in? && @subject.user == current_user
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.destroy
  end

  def edit
    redirect_to root_path unless user_signed_in? && @subject.user == current_user
  end

  def update
    render :edit unless @memo.update(memo_params)
  end

  def search
    redirect_to root_path unless user_signed_in? && @subject.user == current_user
    @subjects = Subject.where(user_id: current_user.id).where.not(id: params[:subject_id])
    @memos = Memo.search(params[:keyword]).where(subject_id: params[:subject_id]).order(created_at: 'DESC')
  end

  private

  def set_subject
    @subject = Subject.find(params[:subject_id])
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:topic, :image, :point, :explanation).merge(user_id: current_user.id)
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/create.html.erb
<%= render "shared/memo_header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">メモを作成しました!</h2>
    </div>
  </div>
  <div class='feature-lists'>
    <div class='list'>
      <%= link_to "ルームへ", subject_memos_path(@subject), class: 'link-room' %>
    </div>
    <div class='list'>
      <%= link_to "一覧ページに戻る", subjects_path, class: 'link-top' %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/memos/destroy.html.erb
<%= render "shared/memo_header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">メモを削除しました</h2>
    </div>
  </div>
  <ul class='feature-lists'>
    <li class='list'>
      <%= link_to "ルームに戻る", subject_memos_path(@subject), class:"link-top" %>
    </li>
  </ul>
</div>

<%= render "shared/footer" %>

app/views/memos/edit.html.erb
<%= render "shared/memo_header"%>

<div class="registration-body">
  <%= form_with model: [@subject, @memo], url: subject_memo_path, class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        メモ情報の編集
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :topic, "メモの題名", class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :topic, class:"input-default", maxlength:"40" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <label class="form-text">スクリーンショット等画像</label>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, class:"room-image" %>
      </div>
    </div>

    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :point, "関係する記述（コードや問題文等）を書きましょう", class:"form-text" %>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_area :point, class:"input-contents" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :explanation, "メモを書きましょう", class:"form-text" %>
        <span class="indispensable">任意</span>
      </div>
      <div id="editor" class="memo-explanation">
        <%= f.text_area :explanation, placeholder:"マークダウン記法が可能です", class:"input-memo-explanation", "v-model" => "input", name: "memo[explanation]" %>
      </div>
    </div>
    <div class='register-btn'>
      <%= f.submit "メモ更新" ,class:"register-link" %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/memos/index.html.erb
<%= render "shared/memo_header" %>
<div class="memo-wrapper">
  <div class="memo-side">
    <%= render "shared/memo_side_bar" %>
  </div>

  <div class="memo-main">
    <%= render "shared/memo_main" %>
  </div>
</div>
<div class="subject-destroy">
  <%= link_to "科目ルームの削除", subject_path(@subject), method: :delete, class: 'subject-destroy-link', data: { confirm: "本当に削除しますか？" } %>
</div>

<%= render "shared/footer"%>

app/views/memos/new.html.erb
<%= render "shared/memo_header"%>

<div class="registration-body">
  <%= form_with model: [@subject, @memo], url: subject_memos_path, class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        メモの作成
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :topic, "メモの題名", class:"form-text" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :topic, class:"input-default", maxlength:"40" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <label class="form-text">スクリーンショット等画像</label>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, class:"room-image" %>
      </div>
    </div>

    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :point, "関係する記述（コードや問題文等）を書きましょう", class:"form-text" %>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_area :point, class:"input-contents" %>
    </div>
    <div class="form-group-wide">
      <div class='form-text-wrap'>
        <%= f.label :explanation, "メモを書きましょう", class:"form-text" %>
        <span class="indispensable">任意</span>
      </div>
      <div id="editor" class="memo-explanation">
        <%= f.text_area :explanation, placeholder:"マークダウン記法が可能です", class:"input-memo-explanation", "v-model" => "input", name: "memo[explanation]" %>
      </div>
    </div>
    <div class='register-btn'>
      <%= f.submit "メモ作成" ,class:"register-link" %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/memos/search.html.erb
<%= render "shared/memo_header" %>
<div class="memo-wrapper">
  <div class="memo-side">
    <%= render "shared/memo_side_bar" %>
  </div>

  <div class="memo-main">
    <%= render "shared/memo_main" %>
  </div>
</div>
<div class="subject-destroy">
  <%= link_to "科目ルームの削除", subject_path(@subject), method: :delete, class: 'subject-destroy-link', data: { confirm: "本当に削除しますか？" } %>
</div>

<%= render "shared/footer"%>

app/views/memos/show.html.erb
<%= render "shared/memo_header" %>
<div class="memo-show-main">
  <div class="memo-text">
    <h2 class="form-text">題目</h2>
  </div>
  <div class="memo-show-title">
    <%= @memo.topic %>
  </div>
  <div class="memo-text">
    <h2 class="form-text">該当箇所の画像</h2>
  </div>
  <div class="memo-show-image">
    <%= link_to image_tag(@memo.image.variant(resize: '200x200')),@memo.image, :rel => "lightbox", class: "memo-img" if @memo.image.attached? %>
  </div>
  <div class="memo-text">
    <h2 class="form-text">関連する記述</h2>
  </div>
  <div class="memo-show-contents">
    <%= @memo.point %>
  </div>
  <div class="memo-text">
    <h2 class="form-text">メモ</h2>
  </div>
  <div class="memo-show-markdown" id="memo-show-markdown">
    <%= sanitize markdown(@memo.explanation), tags: %w(h1 h2 h3 h4 h5 strong em a p ul li code pre a), attributes: %w(href) %>
  </div>
  <div class="memo-show-btn">
    <%= link_to "編集", edit_subject_memo_path(@subject, @memo), class:"btn-edit-destroy" %>
    <%= link_to "削除", subject_memo_path(@subject, @memo), method: :delete, class:"btn-edit-destroy", data: { confirm: "本当に削除しますか？" } %>
  </div>
  <div class="memo-show-back">
    <%= link_to "メモ一覧に戻る", subject_memos_path(@subject), class:"memo-show-top" %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/memos/update.html.erb
<%= render "shared/memo_header" %>
<div class="room-create-contents">
  <div class="message">
    <div class="success">
      <h2 class="create-message">メモを編集しました!</h2>
    </div>
  </div>
  <div class='feature-lists'>
    <div class='list'>
      <%= link_to "ルームへ", subject_memos_path(@subject), class: 'link-room' %>
    </div>
    <div class='list'>
      <%= link_to "一覧ページに戻る", subjects_path, class: 'link-top' %>
    </div>
  </ul>
</div>

<%= render "shared/footer" %>